name: tagpr
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: Songmu/tagpr@9d0f650553240dab1fa907eca27e3fd5b586e538 # v1.18.1
      id: tagpr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "steps.tagpr.outputs.tag != ''"
